DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS events_to_compilations CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    name  VARCHAR(250) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lon FLOAT  NOT NULL,
    lat FLOAT  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(2000),
    category           BIGINT,
    confirmed_requests INTEGER,
    created_on         TIMESTAMP,
    description        VARCHAR(7000),
    event_date         TIMESTAMP,
    initiator          BIGINT,
    location           BIGINT,
    paid               BOOLEAN,
    participant_limit  BIGINT,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN,
    state              VARCHAR(30),
    title              VARCHAR(120),
    views              BIGINT,
    CONSTRAINT events_to_categories_fk FOREIGN KEY (category) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT events_to_locations_fk FOREIGN KEY (location) REFERENCES locations (id) ON DELETE CASCADE,
    CONSTRAINT events_to_users_fk FOREIGN KEY (initiator) REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created   TIMESTAMP,
    event     BIGINT NOT NULL,
    requester BIGINT NOT NULL,
    status    VARCHAR(100) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT requests_to_events_fk FOREIGN KEY (event) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT requests_to_users_fk FOREIGN KEY (requester) REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(250) NOT NULL UNIQUE,
    pinned BOOLEAN,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_to_compilations (
    event_id       BIGINT,
    compilation_id BIGINT,
    CONSTRAINT compilations_fk FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT events_fk FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content  VARCHAR(700),
    created  TIMESTAMP,
    user_id  BIGINT,
    event_id BIGINT,
    CONSTRAINT fk_comment_to_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_comment_to_events FOREIGN KEY (event_id) REFERENCES events (id),
    PRIMARY KEY (id)
);
